[package]
name = "spectra-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "OpenSpectra command-line interface."

[[bin]]
name = "spectra"
path = "src/main.rs"

[dependencies]
spectra-core = { path = "../spectra-core" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
clap.workspace = true
