//! @generated by scripts/capture-update-templates.py against
//! the reference binary v3.0.0 -- do not edit by hand.
//!
//! Registry order and detection directories are oracle behavior;
//! see docs/reverse-engineering/update.md.

use crate::update::{FileKind, FileSpec, ToolDef};

pub static TOOLS: &[ToolDef] = &[
    ToolDef {
        id: "antigravity",
        detect_dir: ".agent",
        files: &[
            FileSpec {
                relpath: ".agent/skills/spectra-apply/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/6868c1f09c2a.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-archive/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/80102c7b7335.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-audit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/8fe67479c2ae.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-commit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/04cf313415a3.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-debug/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/31557e9a25e2.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-discuss/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/dfe086e7a306.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-drift/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/4f3291bb823d.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-ingest/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/3baab7ee8e22.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-propose/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/7cb4c10927b5.md"),
            },
            FileSpec {
                relpath: ".agent/skills/spectra-review/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/297852a01ac6.md"),
            },
            FileSpec {
                relpath: "GEMINI.md",
                kind: FileKind::Managed,
                template: include_str!("../assets/update/9d3683c9f7df.md"),
            },
        ],
    },
    ToolDef {
        id: "claude",
        detect_dir: ".claude",
        files: &[
            FileSpec {
                relpath: ".claude/settings.json",
                kind: FileKind::ClaudeSettings,
                template: include_str!("../assets/update/fd50f0952556.json"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-analyze/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/39fa4aab0f43.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-apply/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/19c98d42d2a8.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-archive/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/ad68a69a2026.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-audit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/1027c1257367.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-commit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/bbbdadf148d4.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-debug/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/357d9ca63abe.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-discuss/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/a44e83900071.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-drift/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/da8f4300ad0d.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-ingest/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/59a86e3e4478.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-propose/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/4a30a5533ce4.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-review/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/f98ab3d37eea.md"),
            },
            FileSpec {
                relpath: ".claude/skills/spectra-verify/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/50a41919f2b7.md"),
            },
            FileSpec {
                relpath: "CLAUDE.md",
                kind: FileKind::Managed,
                template: include_str!("../assets/update/9d3683c9f7df.md"),
            },
        ],
    },
    ToolDef {
        id: "codex",
        detect_dir: ".agents",
        files: &[
            FileSpec {
                relpath: ".agents/skills/spectra-analyze/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/507f2f2a2506.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-apply/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/20236f585ae4.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-archive/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/f8be65e67eb8.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-audit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/8fe67479c2ae.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-commit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/da4348c6690b.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-debug/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/e493395f89ef.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-discuss/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/bb58e267b44f.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-drift/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/049e92251e3a.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-ingest/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/f6808966593f.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-propose/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/cb5208a50657.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-review/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/923242917be1.md"),
            },
            FileSpec {
                relpath: ".agents/skills/spectra-verify/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/dcf031e60e2e.md"),
            },
            FileSpec {
                relpath: "AGENTS.md",
                kind: FileKind::Managed,
                template: include_str!("../assets/update/6e52d140fd24.md"),
            },
        ],
    },
    ToolDef {
        id: "cursor",
        detect_dir: ".cursor",
        files: &[
            FileSpec {
                relpath: ".cursor/skills/spectra-apply/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/6868c1f09c2a.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-archive/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/80102c7b7335.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-audit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/8fe67479c2ae.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-commit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/b65988a2369a.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-debug/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/31557e9a25e2.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-discuss/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/dfe086e7a306.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-drift/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/4f3291bb823d.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-ingest/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/f1e5513f892e.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-propose/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/2682c99fc6bb.md"),
            },
            FileSpec {
                relpath: ".cursor/skills/spectra-review/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/297852a01ac6.md"),
            },
            FileSpec {
                relpath: ".cursorrules",
                kind: FileKind::Managed,
                template: include_str!("../assets/update/b7abb6d2f354.txt"),
            },
        ],
    },
    ToolDef {
        id: "github-copilot",
        detect_dir: ".github",
        files: &[
            FileSpec {
                relpath: ".github/skills/spectra-analyze/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/fd46a84785de.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-apply/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/6868c1f09c2a.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-archive/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/80102c7b7335.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-audit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/8fe67479c2ae.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-commit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/040d8aec511b.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-debug/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/31557e9a25e2.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-discuss/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/dfe086e7a306.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-drift/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/4f3291bb823d.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-ingest/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/3baab7ee8e22.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-propose/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/350eedff8ff2.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-review/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/297852a01ac6.md"),
            },
            FileSpec {
                relpath: ".github/skills/spectra-verify/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/d1c88d1f5d95.md"),
            },
        ],
    },
    ToolDef {
        id: "junie",
        detect_dir: ".junie",
        files: &[
            FileSpec {
                relpath: ".junie/AGENTS.md",
                kind: FileKind::Managed,
                template: include_str!("../assets/update/9d3683c9f7df.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-apply/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/19c98d42d2a8.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-archive/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/ad68a69a2026.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-audit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/8fe67479c2ae.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-commit/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/21ab7c937af7.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-debug/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/357d9ca63abe.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-discuss/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/a44e83900071.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-drift/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/6153e0efd5f4.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-ingest/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/b7532363cf05.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-propose/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/49d48c897728.md"),
            },
            FileSpec {
                relpath: ".junie/skills/spectra-review/SKILL.md",
                kind: FileKind::Plain,
                template: include_str!("../assets/update/133de800eaf7.md"),
            },
        ],
    },
];
